<?php
/**
 * Export + legacy report coverage (4.6 / 4.7).
 *
 * @package maz-allowlist
 */

defined( 'ABSPATH' ) || exit;

/**
 * Coverage notes:
 *
 * - Analytics "Download" button (4.6): both download paths re-run the report
 *   queries — small result sets are exported client-side from the already
 *   filtered REST payload; large ones are generated by ReportCSVExporter in
 *   Action Scheduler. Both go through the Analytics data stores, and the
 *   Analytics module registers its clause filters on every request type
 *   (including cron), so exports match what the UI shows. Background export
 *   jobs run with no user context, so they are ALWAYS filtered while rules
 *   are active — even when triggered by a bypass-capability admin (documented
 *   in the README).
 *
 * - Orders CSV exporter (4.6): WooCommerce core ships no orders CSV exporter
 *   (only products). Third-party order exporters that query the data store
 *   directly are NOT covered — see README.
 *
 * - Legacy WooCommerce → Reports (4.7): handled below via
 *   woocommerce_reports_get_order_report_query, which every WC_Admin_Report
 *   query (screens, their CSV export links, and the dashboard sales widget)
 *   passes through. Note these reports read wp_posts; on an HPOS site
 *   without compatibility sync they are inaccurate regardless of this plugin.
 */
class Maz_Allowlist_Exports {

	/**
	 * Wire hooks.
	 */
	public static function init() {
		add_filter( 'woocommerce_reports_get_order_report_query', array( __CLASS__, 'filter_legacy_report_query' ) );
	}

	/**
	 * Inject visibility JOIN/WHERE into legacy WC_Admin_Report queries.
	 * These queries use "FROM wp_posts AS posts".
	 *
	 * @param mixed $query Assoc array of SQL parts (select/from/join/where/...).
	 * @return mixed
	 */
	public static function filter_legacy_report_query( $query ) {
		if ( ! is_array( $query ) || ! is_admin() || ! maz_allowlist_filtering_active() ) {
			return $query;
		}

		$existing = ( isset( $query['join'] ) ? (string) $query['join'] : '' ) . ( isset( $query['where'] ) ? (string) $query['where'] : '' );
		if ( false !== strpos( $existing, 'maz_' ) ) {
			return $query; // Already injected.
		}

		$fragments = maz_visibility_sql_clause( 'legacy_reports' );
		if ( '' === $fragments['where'] ) {
			return $query;
		}

		$query['join']  = ( isset( $query['join'] ) ? $query['join'] . ' ' : '' ) . implode( ' ', $fragments['join'] );
		$query['where'] = ( isset( $query['where'] ) ? $query['where'] . ' ' : '' ) . 'AND /* maz_allowlist */ ' . $fragments['where'];
		return $query;
	}
}
